Fix "delete-all"
It was broken by 14ed8b12, resulting in:

    $ jenkins-jobs delete-all
    Traceback (most recent call last):
      File "/Users/marca/python/virtualenvs/jenkins-job-builder/bin/jenkins-jobs", line 10, in <module>
        sys.exit(main())
      File "/Users/marca/dev/git-repos/jenkins-job-builder/jenkins_jobs/cmd.py", line 143, in main
        if options.path == sys.stdin:
    AttributeError: 'Namespace' object has no attribute 'path'

Change-Id: I42a3ef9f3cfca7b4667498009351e0027aa316d7